name: Update Blacklist and Create PR Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-blacklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run blocklists-dl.sh
        run: |
          chmod +x blocklists-dl.sh
          ./blocklists-dl.sh

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: update-blacklist
          author_name: "${{ github.actor }}"
          author_email: "${{ github.actor }}@users.noreply.github.com"
          message: "Update blacklist via GitHub Action"
          add: "mikrotik-blacklist.rsc"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          title: "Update blacklist via GitHub Action"
          commit-message: "Update blacklist via GitHub Action"
